### PR TITLE
Add COS226 grading notifications

### PR DESCRIPTION
**Pull request by nicholaspad**
## Summary

Adds all COS226 assignments (name, start date, due date) to `config.yaml` along with the COS 226 Notifications Slack channel metadata. Due dates come from cos226.com, and start dates are set to one day after the previous assignment's due date. Percolation's start date is the first day of classes.

Not sure why the automated test is failing @josephlou5 @jlumbroso

### CODE REVIEW

**Comment by josephlou5** [comment]
1. Can you make sure all the assignment names match up with their names on codePost? Here is a screenshot of the logs of the action running due to your commit, which shows that there is no assignment named "Wordnet" (it's called "WordNet" on codePost):
image

2. The `"start"` and `"end"` dates aren't the dates that the students are completing the assignment. The date range defines when the script should run, which would be when the assignments are being graded. For example, we are currently grading the Classifier assignment for COS126, which is why the date range for that is `2022-11-02` (yesterday) to `2022-11-08` (next Tuesday, when we'll hopefully be done grading it). Think about when you want graders to be able to see notifications that say "X% of [assignment] is done!".

**Comment by jlumbroso** [comment]
What's happening is that the continuous integration that is being run is not automated checks, but a "cronjob" (triggered by the commit) to generate data and commit it to the repository. The problem is that the pull request is not at the HEAD of the repository, it's on a different branch, and so while I don't understand the specific interaction, the problem is that this automated script is trying to commit data while the pull request is being submitted.
Think about it, you wouldn't want an attacker to be able to commit random data to your repo by creating a pull request.
So:
- it may be a good idea to have continuous integration tests that check whether the code is correct
- the current script is not that, it shouldn't be expected to run during a pull request, it's not meant to _verify whether in this case Nick's code is correct_, it's supposed to _run Nick's code_.

Does that make sense?

**Review by jlumbroso — CHANGES_REQUESTED** [review]
@nicholaspad As @josephlou5 said, you need to match the codePost names exactly because those strings are used to make calls to the codePost API.

Besides `Wordnet` -> `WordNet`, I think there's also a few others. Here are the names from codePost (you need to include spaces):

image

**Comment by nicholaspad** [comment]
@jlumbroso @josephlou5 ah, didn't realize that the names have to match those in codePost and that the date intervals should align with grading periods. Will fix!

**Comment by nicholaspad** [comment]
Fixed everything up. A couple notes:

- The start date is always the Wednesday immediately after each assignment is due, except for Seam Carving because that Wednesday is during Thanksgiving
- The end date is always 5 days after the start date - I assume that grading tends to finish within this timeframe

**Review by jlumbroso — CHANGES_REQUESTED** [review]
@nicholaspad Sorry for underspecifying, but actually now that you point it out, I think the duration of each interval should 2 weeks, because of late submissions that pop up at any random time — and the late submissions are one of the important "problems" that this solves, _i.e._ as grading managers (and as faculty oversight), it's create not to have to remember to advertise to the channel when any old late submissions falls into the pile.

Sorry for not giving you all the constraints ahead of time 😊

**Comment by nicholaspad** [comment]
No problem, it's a very minor change!

**Review by jlumbroso — APPROVED** [review]
Thanks @nicholaspad !

**Pull request merged**
